### PR TITLE
stat_count() & stat_tally() better handle variables that are neither factors nor character vectors

### PR DESCRIPTION
**Pull request by tzoltak**
In response to #102 I reworked how survey_stat_factor() handle variables that are neither factors nor character vectors.

### CODE REVIEW

**Comment by tzoltak** [comment]
Sorry for to much haste and not making tests. I will correct myself.

**Comment by gergness** [comment]
Thanks, but I think #89 fixes this already so im not sure this is necessary. I just need to find time to finish that pr

**Comment by tzoltak** [comment]
I'm looking forward for #89 nevertheless my patch to survey_stat_factor() now seems to work fine (these GitHub tests seem to fail due to some configuration problem). Perhaps you will introduce it, if you know that getting #89 done will take you some more time.

**Comment by gergness** [comment]
Sorry, I really wanted to just fix this via #89, hope this worked for you in the interim!

**Pull request closed without merging**
