### PR TITLE
Update usage of deprecated functions from dplyr

### PR DESCRIPTION
**Pull request by bschneidr**
Replace instances of deprecated functions from dplyr.

Specifically, the following replacements have been made:

- `dplyr::data_frame()` -> `tibble::tibble()`
- `dplyr::as_data_frame()` -> `tibble::as_tibble()`
- `dplyr::tbl_df()` -> `tibble::as_tibble()`
- `dplyr::select_vars()` -> `tidyselect::vars_select()`

Because of the use of `tidyselect::vars_select()`, the `tidyselect` package has been added to `Imports`

### CODE REVIEW

**Comment by bschneidr** [comment]
I believe the checks failed because the `MonetDBLite` package was [withdrawn from CRAN](https://cran.r-project.org/web/packages/MonetDBLite/index.html) and [apparently will be eventually replaced by the `duckdb` package.](https://github.com/MonetDB/MonetDBLite-R/issues/38)

**Comment by gergness** [comment]
Amazing, thanks! Please add your name as an author in the DESCRIPTION field. 

I think I have at least one more release in me, but please do let me know if you are interested in taking over maintainership. I'm worried that my ability to keep up with this is slowing and I'm no longer using survey data in my day to day job.

**Comment by bschneidr** [comment]
Gladly, Greg. I noticed from one of the issues that you seemed pretty busy with work/life stuff and I figured this would be a simple thing to take off your plate.

I definitely would be interested in taking over maintainership if you're going to be stepping away from the package. In a couple of months I'll be starting a master's in survey methodology so it's a safe bet I will be working with survey data and using the `srvyr` package for at least a few years yet. If you do end up stepping away from the package, I'd like to be able to contribute before your last release by helping resolve filed issues and contributing documentation, tests, and refactoring.

If you do decide to pass on the maintainership or want to explore that route, I can give you a call or we can correspond in an issue thread or by email to talk about what that transition would look like.

**Comment by gergness** [comment]
Ha, awesome, I almost can't believe my luck in finding an appropriate maintainer, though I will warn you that most of the srvyr upkeep is trying to keep up with the tidyverse team (as you see in this PR). 

Why don't you send me an email to greg.fr.ellis [at] gmail.com and we'll discuss next steps.

**Comment by gergness** [comment]
Hey, realized I never saw an email from you. Did I miss it?

**Pull request merged**
